### ISSUE TITLE
Remove eventTime and serviceContext

### ISSUE THREAD

**Issue by 1602** [universalbasket/ub-logger#12]
It looks like they doesn't do anything useful anymore. Transferred from https://github.com/universalbasket/hive/issues/624

https://github.com/universalbasket/ub-logger/blob/5b07eb0cb6b11e0e94c3fc85e6d47cfce9d2b13a/lib/stack-driver-transform.js#L8
https://github.com/universalbasket/ub-logger/blob/0514d672244baabbe685e7073db087d3d7a37095/lib/make-logger.js#L7

**Comment by emmasalih** [comment]
moved
